[package]
name = "convco"
version = "0.1.0"
license = "MIT"
authors = ["Hannes De Valkeneer <hannes@de-valkeneer.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.10", features = ["serde"] }
git2 = "0.10.2"
handlebars = "2.0.2"
lazy_static = "1.4.0"
regex = "1.3.1"
semver = { version = "0.9.0", features = ["serde"] }
serde = { version = "1.0.103", features = ["derive"] }
serde_yaml = "0.8.11"
structopt = "0.3.5"
