[package]
name = "convco"
version = "0.1.0"
description = "Conventional commit tools"
keywords = ["conventional", "commit", "changelog", "semantic", "versioning"]
categories = ["development-tools::build-utils"]
readme = "README.md"
repository = "https://github.com/hdevalke/convco.git"
license = "MIT"
authors = ["Hannes De Valkeneer <hannes@de-valkeneer.be>"]
edition = "2018"
exclude = [
    ".*",
]

[dependencies]
chrono = { version = "0.4.10", features = ["serde"] }
git2 = { version = "0.11.0", default-features = false, features = [] }
handlebars = "2.0.2"
lazy_static = "1.4.0"
regex = "1.3.1"
semver = { version = "0.9.0", features = ["serde"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_yaml = "0.8.11"
structopt = "0.3.5"

[build-dependencies]
structopt = "0.3.5"

[package.metadata.deb]
depends = ""
extended-description = """\
Conventional commit tools. \
Create a changelog. \
Check if commits follow the convention. \
Calculate the next version based on the conventional commits."""
assets = [
    # bin
    ["target/release/convco", "/usr/local/bin/", "755"],
    # completions
    ["target/completions/convco.bash", "/usr/share/bash-completion/completions/", "644"],
    ["target/completions/_convco", "/usr/share/zsh/vendor-completions/", "644"],
    ["target/completions/convco.fish", "/usr/share/fish/completions/", "644"],
]
