[package]
name = "convco"
version = "0.3.11"
description = "Conventional commit tools"
keywords = ["conventional", "commit", "changelog", "semantic", "versioning"]
categories = ["development-tools::build-utils"]
readme = "README.md"
homepage = "https://convco.github.io"
repository = "https://github.com/convco/convco.git"
license = "MIT"
authors = ["Hannes De Valkeneer <hannes@de-valkeneer.be>"]
edition = "2021"
include = [
    "build.rs",
    "src/*",
    "README.md",
    "LICENSE"
]

[dependencies]
anyhow = { version = "1.0.62", features = ["backtrace"] }
clap = { version = "3.2.17", features = ["derive"] }
ctrlc = "3.2.3"
dialoguer = "0.10.2"
git2 = { version = "0.15.0", default-features = false, features = [ "zlib-ng-compat" ] }
handlebars = "4.3.3"
regex = "1.6.0"
semver = "1.0.13"
serde = { version = "1.0.143", features = ["derive"] }
serde_yaml = "0.9.9"
thiserror = "1.0.32"
time = { version = "0.3.13", features = [ "serde-human-readable" ] }
url = "2.2.2"
walkdir = "2.3.2"

[build-dependencies]
clap = { version = "3.2.17", features = ["derive"] }
clap_complete = "3.2.4"

[package.metadata.deb]
depends = ""
extended-description = """\
Conventional commit tools. \
Create a changelog. \
Check if commits follow the convention. \
Calculate the next version based on the conventional commits."""
assets = [
    # bin
    ["target/release/convco", "/usr/local/bin/", "755"],
    # completions
    ["target/completions/convco.bash", "/usr/share/bash-completion/completions/", "644"],
    ["target/completions/_convco", "/usr/share/zsh/vendor-completions/", "644"],
    ["target/completions/convco.fish", "/usr/share/fish/completions/", "644"],
]
